// app/(backend)/admin/testimonials/data.ts
export const mockTestimonials = [
  {
    id: 1,
    author: "Sarah Chen",
    role: "Tech Entrepreneur",
    quote: "The entire process was seamless. Found our dream home in just 3 weeks!",
    rating: 5,
    image: "https://images.unsplash.com/photo-1494790108755-2616b786d4d1?ixlib=rb-4.0.3&auto=format&fit=crop&w=987&q=80",
    status: "published",
    featured: true,
    createdAt: "2024-01-15",
  },
  {
    id: 2,
    author: "Michael Rodriguez",
    role: "Investment Banker",
    quote: "Professional service from start to finish. The team really understands luxury real estate.",
    rating: 5,
    image: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-4.0.3&auto=format&fit=crop&w=2070&q=80",
    status: "published",
    featured: true,
    createdAt: "2024-01-18",
  },
  {
    id: 3,
    author: "Jessica Williams",
    role: "Interior Designer",
    quote: "Exceeded all expectations. The property valuation was spot on and helped us sell above asking price.",
    rating: 5,
    image: "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?ixlib=rb-4.0.3&auto=format&fit=crop&w=2071&q=80",
    status: "published",
    featured: false,
    createdAt: "2024-01-20",
  },
  {
    id: 4,
    author: "David Kim",
    role: "Real Estate Investor",
    quote: "Amazing experience! They found us a perfect investment property that's already appreciating.",
    rating: 5,
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?ixlib=rb-4.0.3&auto=format&fit=crop&w=987&q=80",
    status: "pending",
    featured: false,
    createdAt: "2024-02-01",
  },
  {
    id: 5,
    author: "Alex & Taylor Morgan",
    role: "First-time Buyers",
    quote: "Patient, knowledgeable, and always available. Made our first home buying experience stress-free.",
    rating: 5,
    image: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?ixlib=rb-4.0.3&auto=format&fit=crop&w=987&q=80",
    status: "draft",
    featured: false,
    createdAt: "2024-02-05",
  },
  {
    id: 6,
    author: "Emily Watson",
    role: "Luxury Home Buyer",
    quote: "Found us an incredible property that exceeded all our expectations. The attention to detail was remarkable.",
    rating: 4,
    image: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?ixlib=rb-4.0.3&auto=format&fit=crop&w=2070&q=80",
    status: "archived",
    featured: false,
    createdAt: "2024-02-10",
  }
];